issue_templates:
  bug:
    name: 'Bug Report'
    description: 'Describe the bug'
    labels: ['bug']
    assignees: ['octocat']
  todo:
    name: 'To-Do Item'
    description: 'Create a task'
    labels: ['todo']
    assignees: ['octocat']
  blank:
    name: 'Blank Issue'
    description: 'Create an issue without a template'
    labels: []
    assignees: ['octocat']
